### ISSUE TITLE
[Issue] idk if u know, but outside enemies cannot stand on the frozen water, mesh question, and heavy framerate drop when playing with blizzard weather

### ISSUE THREAD

**Issue by CoolLKKPS** [v0xx-dev/VoxxWeatherPlugin#1]
especially outside enemies cannot stand on the frozen water, if i enable frozen water config option, no matter terrain mesh are enabled or not, the enemies should can stand on the frozen water not just dive into the water.
for me i disabled all terrain mesh to prevent conflict, bc i think this is a potentially conflicting feature, and idk how it work.
and heavy framerate drop, can i limit the snow or some effects framerate? bc that cost too much performance issue.
and i do like ur mod, but i really don't know how to correctly set this mod config for better performance, my DH modpack link here hope u can help me a bit: https://1drv.ms/f/c/c26722dc35962b5c/ElwrljXcImcggMKLCgAAAAABXdwXiAVT3j3zNnyNZw3uXg
thx in advance for ur reply.

**Comment by v0xx-dev** [comment]
> especially outside enemies cannot stand on the frozen water, if i enable frozen water config option, no matter terrain mesh are enabled or not, the enemies should can stand on the frozen water not just dive into the water. for me i disabled all terrain mesh to prevent conflict, bc i think this is a potentially conflicting feature, and idk how it work. and heavy framerate drop, can i limit the snow or some effects framerate? bc that cost too much performance issue. and i do like ur mod, but i really don't know how to correctly set this mod config for better performance, my DH modpack link here hope u can help me a bit: https://1drv.ms/f/c/c26722dc35962b5c/ElwrljXcImcggMKLCgAAAAABXdwXiAVT3j3zNnyNZw3uXg thx in advance for ur reply.

I fixed the issue with enemies and ice in v1.2.50.
You cannot disable terrain mesh features because it's one of the core functions of this mod, without it blizzard and snowfall will not work on custom moons.
If you have severe framerate drops unfortunately it means you computer is not enough, there will be options to reduce the number of particles in the future, but it won't magically solve all of the problems. Sorry!

**Comment by CoolLKKPS** [comment]
okay anyway, i will do more test about this mod, at this moment this mod seems that every time u return to the main menu, there will be an error log related to this mod, but it shouldn't have any impact i think
